version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Login_user
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./front-end:/var/www/html
      - ./back-end:/var/www/html/back-end
    depends_on:
      - mysql

  grafana:
    image: grafana/grafana:11.2.0
    ports:
      - "3000:3000"
    container_name: grafana
    restart: unless-stopped
    networks:
      - todo
    volumes:
      - grafana:/var/lib/grafana
      - ./monitor/grafana.ini:/etc/grafana/grafana.ini

  prometheus:
    image: prom/prometheus:v2.48.0
    ports:
      - "9090:9090"
    networks:
      - todo
    volumes:
      - prometheus:/prometheus
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml

  exporter:
    image: prom/node-exporter:latest
    container_name: exporter
    ports:
      - "9100:9100"
    networks:
      - todo
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"

volumes:
  mysql: